### ISSUE TITLE
Testverktyg?

### ISSUE THREAD

**Issue by Toubic** [1DV611/effect-reklambyra#18]
Vilka testverktyg ska vi använda?

**Comment by Toubic** [comment]
Nightwatch.js? (http://nightwatchjs.org/)
nodeunit? (https://www.npmjs.com/package/nodeunit)

**Comment by meristakovska** [comment]
TDD/BDD?

[Jasmine](https://jasmine.github.io/), [mocha](https://mochajs.org/), [chai](http://chaijs.com/), [sinon](http://sinonjs.org/)?

**Comment by sehnpaa** [comment]
Jag började kolla på nightwatch.js för att hitta någon integrationslösning för test och kom vidare in på Selenium, vilket i sin tur förde mig in på webdrivers. WebdriverIO är Selenium-bindings med en inbyggd testrunner. Den håller jag på att fila på nu. Man kör igång en headless Selenium-server som har en Geckodriver (en "webdriver") och så låter man testrunnern prata med servern via dessa bindings: http://webdriver.io/api.html. Ovanpå bakas Mocha och Chai in så testen kan ser ut exempelvis så här:

```
describe('my awesome website', function() {
    it('should do some chai assertions', function() {
        browser.url('http://webdriver.io');
        browser.getTitle().should.be.equal('WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
    });
});
```

Nackdelen, som jag ser det nu, med den här setup:en är alla dependencies som behövs: En .jar-fil för Seleninum, Java (openjdk-8-jre fungerar i Debian Stretch) för att köra den, Xvfb för att fejka en X11-server och Geckodrivern (0.11 fungerade, inte senaste (0.15)) känns som det värsta. Dock möjligt att det går att jobba bort i efterhand; jag har inte tittat på det ännu.

Det här kommer vi alltså prova med på klientsidan. På servernsidan får vi se... Förhoppningsvis dröjer det inte allt för länge innan vi har kolla på vad för serialiserade datastrukturer som kommer skickas mellan klient, server, databas och socialamedier...

Hur som helst, att göra nu är att snygga upp lite och sedan merga med master. Därefter ska jag börja skriva ett par testfall som är relevanta för vår UI-mockup.

**Comment by meristakovska** [comment]
Jag lyckas inte köra testet:

10:55:50.576 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException

Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException

Caused by: java.lang.reflect.InvocationTargetException

Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:26779 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1] failed: Connection refused (Connection refused)

Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:26779 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1] failed: Connection refused (Connection refused)

Caused by: java.net.ConnectException: Connection refused (Connection refused)

10:56:10.687 WARN - Exception: Connection refused (Connection refused)
ERROR: Connection refused (Connection refused)
firefox
Error: Connection refused (Connection refused)

**Comment by sehnpaa** [comment]
Tack för testen!
Vad händer om du står i projektets rootmapp och kör `java -jar -Dwebdriver.gecko.driver=./tests/geckodriver_0_11 ./tests/selenium-server-standalone-3.0.1.jar`?

**Comment by meristakovska** [comment]
12:30:07.354 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
12:30:07.356 INFO - Launching a standalone Selenium Server
2017-04-05 12:30:07.412:INFO::main: Logging initialized @858ms
12:30:07.563 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
12:30:07.563 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
12:30:07.564 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:30:07.564 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
12:30:07.564 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:30:07.564 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
2017-04-05 12:30:07.681:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-04-05 12:30:07.753:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@215be6bb{/,null,AVAILABLE}
2017-04-05 12:30:07.850:INFO:osjs.ServerConnector:main: Started ServerConnector@28feb3fa{HTTP/1.1}{0.0.0.0:4444}
2017-04-05 12:30:07.851:INFO:osjs.Server:main: Started @1297ms
12:30:07.851 INFO - Selenium Server is up and running

**Comment by sehnpaa** [comment]
Efter att ha provat själv på Windows 7 kom jag fram till något som verkade fungera. Har mergat lösningen in i master via #39.

För övrigt, de testverktyg som jag anser lämpliga har jag nämnt i den tekniska dokumentationen i wiki:n, så härmed förklarar jag orginalfrågan besvarad.
